modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="epicfightgodskill"
version="1.0.0"
displayName="EpicFight GodSkill"
description='''
EpicFight addon that adds overpowered skills.
'''

[[dependencies.epicfightgodskill]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.epicfightgodskill]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.epicfightgodskill]]
    modId="epicfight"
    mandatory=true
    versionRange="[20,)"
    ordering="AFTER"
    side="BOTH"

[[mixins]]
config="epicfightgodskill.mixins.json"
